name: vs_scrollbar
description: Customizable ScrollBar that can be dragged for quick navigation supporting both Horizontal and Vertical list.
version: 0.2.1
homepage: https://github.com/VickySalunkhe/vs_scrollbar
repository: https://github.com/VickySalunkhe/vs_scrollbar

environment:
  sdk: ">=3.0.0<4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: